/**
 * ASH Thrombophilia Calculator - Recommendation Data
 *
 * This data is extracted from the Excel calculator:
 * "4.ASH-Threshold-thrombophilia-calculator-Final-withArg_pVTE-.xlsx"
 *
 * Each recommendation contains:
 * - id: Recommendation identifier (R1, R2, etc.)
 * - pVTE: Probability of VTE recurrence without treatment
 * - Tp: Prevalence of thrombophilia in the population
 * - RRt: Relative risk of VTE in thrombophilia positives vs negatives
 * - RRrx: Relative risk of VTE when treated (lower is better, e.g., 0.15 = 85% reduction)
 * - H_low: Baseline major bleeding risk (low risk scenario)
 * - H_high: Baseline major bleeding risk (high risk scenario)
 * - RRbleed: Relative risk of major bleeding with anticoagulant treatment
 * - description: Clinical scenario description
 * - ashRec: ASH guideline recommendation text
 * - ashDecision: ASH decision (NoRx, Test, or Rx)
 * - category: Patient category
 * - group: Calculation sheet group
 * - isReversed: For R15-R20, treatment (COC/HRT) increases VTE risk
 */

const RECOMMENDATIONS = [
    // ==================== R1-R10: Patients with Symptomatic VTE ====================
    {
        id: "R1",
        pVTE: 0.1,
        Tp: 0.38,
        RRt: 1.65,
        RRrx: 0.15,
        H_low: 0.005,
        H_high: 0.015,
        RRbleed: 2.17,
        decimals: 0,
        description: "Patients with unprovoked symptomatic venous thromboembolism who completed primary short-term treatment.",
        ashRec: "For patients with unprovoked VTE who have completed primary short-term treatment, the ASH guideline panel suggests not to perform thrombophilia testing and recommend indefinite anticoagulant treatment to all patients.",
        ashDecision: "Rx",
        category: "Patients with symptomatic VTE",
        group: "R1-R10",
        hasBleedingRiskOption: true
    },
    {
        id: "R2",
        pVTE: 0.01,
        Tp: 0.38,
        RRt: 1.65,
        RRrx: 0.15,
        H_low: 0.005,
        H_high: 0.015,
        RRbleed: 2.17,
        decimals: 0,
        description: "Patients with symptomatic venous thromboembolism provoked by surgery who completed primary short-term treatment.",
        ashRec: "For patients with VTE provoked by surgery who have completed primary short-term treatment, the ASH guideline panel suggests not to perform thrombophilia testing and stopping anticoagulant treatment in all.",
        ashDecision: "NoRx",
        category: "Patients with symptomatic VTE",
        group: "R1-R10",
        hasBleedingRiskOption: true
    },
    {
        id: "R3",
        pVTE: 0.05,
        Tp: 0.38,
        RRt: 1.65,
        RRrx: 0.15,
        H_low: 0.005,
        H_high: 0.015,
        RRbleed: 2.17,
        decimals: 0,
        description: "Patients with symptomatic venous thromboembolism provoked by a non-surgical major transient risk factor who completed primary short-term treatment.",
        ashRec: "The ASH guideline panel suggests testing for thrombophilia and indefinite anticoagulant treatment for patients with thrombophilia and stopping anticoagulant treatment for patients without thrombophilia.",
        ashDecision: "Test",
        category: "Patients with symptomatic VTE",
        group: "R1-R10",
        hasBleedingRiskOption: true
    },
    {
        id: "R4",
        pVTE: 0.05,
        Tp: 0.38,
        RRt: 1.65,
        RRrx: 0.15,
        H_low: 0.005,
        H_high: 0.015,
        RRbleed: 2.17,
        decimals: 0,
        description: "Women with VTE provoked by pregnancy or postpartum who completed primary short-term treatment.",
        ashRec: "The ASH guideline panel suggests thrombophilia testing and indefinite anticoagulant treatment for patients with thrombophilia and stopping anticoagulant treatment for patients without thrombophilia.",
        ashDecision: "Test",
        category: "Patients with symptomatic VTE",
        group: "R1-R10",
        hasBleedingRiskOption: true
    },
    {
        id: "R5",
        pVTE: 0.05,
        Tp: 0.38,
        RRt: 1.65,
        RRrx: 0.15,
        H_low: 0.005,
        H_high: 0.015,
        RRbleed: 2.17,
        decimals: 0,
        description: "Women with VTE associated with use of combined oral contraceptives (COC) who completed primary short-term treatment.",
        ashRec: "The ASH guideline panel suggests testing for thrombophilia and indefinite anticoagulant treatment for patients with thrombophilia and stopping anticoagulant treatment for patients without thrombophilia.",
        ashDecision: "Test",
        category: "Patients with symptomatic VTE",
        group: "R1-R10",
        hasBleedingRiskOption: true
    },
    {
        id: "R6",
        pVTE: 0.075,
        Tp: 0.38,
        RRt: 1.65,
        RRrx: 0.15,
        H_low: 0.005,
        H_high: 0.015,
        RRbleed: 2.17,
        decimals: 0,
        description: "Patients with an unspecified type of venous thromboembolism (not specified as provoked or unprovoked VTE) who completed primary short-term treatment.",
        ashRec: "The ASH guideline panel suggests not performing thrombophilia testing and recommending indefinite anticoagulant treatment to all patients.",
        ashDecision: "Rx",
        category: "Patients with symptomatic VTE",
        group: "R1-R10",
        hasBleedingRiskOption: true
    },
    {
        id: "R7",
        pVTE: 0.038,
        Tp: 0.436,
        RRt: 1.65,
        RRrx: 0.15,
        H_low: 0.005,
        H_high: 0.015,
        RRbleed: 2.17,
        decimals: 0,
        description: "Patients with cerebral venous thrombosis (CVT) in settings when anticoagulation would otherwise be discontinued after primary treatment.",
        ashRec: "The ASH guideline panel suggests thrombophilia testing and indefinite anticoagulant treatment for patients with thrombophilia and stopping anticoagulant treatment for patients without thrombophilia.",
        ashDecision: "Test",
        category: "Patients with symptomatic VTE in unusual sites",
        group: "R1-R10",
        hasBleedingRiskOption: true
    },
    {
        id: "R8",
        pVTE: 0.038,
        Tp: 0.436,
        RRt: 1.65,
        RRrx: 0.15,
        H_low: 0.005,
        H_high: 0.015,
        RRbleed: 2.17,
        decimals: 0,
        description: "Patients with cerebral venous thrombosis (CVT) in settings when anticoagulation would otherwise be continued indefinitely.",
        ashRec: "For patients with CVT who have completed primary treatment, the ASH guideline panel suggests not to perform thrombophilia testing and recommending indefinite anticoagulant treatment to all patients.",
        ashDecision: "Rx",
        category: "Patients with symptomatic VTE in unusual sites",
        group: "R1-R10",
        hasBleedingRiskOption: true
    },
    {
        id: "R9",
        pVTE: 0.05,
        Tp: 0.416,
        RRt: 1.65,
        RRrx: 0.15,
        H_low: 0.005,
        H_high: 0.015,
        RRbleed: 2.17,
        decimals: 0,
        description: "Patients with splanchnic venous thrombosis in settings when anticoagulation would otherwise be discontinued after primary treatment.",
        ashRec: "The ASH guideline panel suggests thrombophilia testing and indefinite anticoagulant treatment for patients with thrombophilia and stopping anticoagulant treatment for patients without thrombophilia.",
        ashDecision: "Test",
        category: "Patients with symptomatic VTE in unusual sites",
        group: "R1-R10",
        hasBleedingRiskOption: true
    },
    {
        id: "R10",
        pVTE: 0.05,
        Tp: 0.416,
        RRt: 1.65,
        RRrx: 0.15,
        H_low: 0.005,
        H_high: 0.015,
        RRbleed: 2.17,
        decimals: 0,
        description: "Patients with splanchnic venous thrombosis in settings when anticoagulation would otherwise be continued indefinitely.",
        ashRec: "The ASH guideline panel suggests not performing thrombophilia testing and recommending indefinite anticoagulant treatment to all patients.",
        ashDecision: "Rx",
        category: "Patients with symptomatic VTE in unusual sites",
        group: "R1-R10",
        hasBleedingRiskOption: true
    },

    // ==================== R11-R14: Asymptomatic Individuals with Family History ====================
    {
        id: "R11a",
        pVTE: 0.015,
        Tp: 0.5,
        RRt: 2.71,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with VTE and Factor V Leiden (FVL) who have a minor provoking VTE risk factor.",
        ashRec: "The ASH guideline panel suggests not testing for the known familial thrombophilia to guide thromboprophylaxis, and not administering thromboprophylaxis in all patients.",
        ashDecision: "NoRx",
        category: "Asymptomatic individuals with family history of VTE - FVL",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R11b",
        pVTE: 0.015,
        Tp: 0.5,
        RRt: 2.35,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with VTE and Prothrombin Gene Mutation (PGM) who have a minor provoking VTE risk factor.",
        ashRec: "The ASH guideline panel suggests not testing for the known familial thrombophilia to guide thromboprophylaxis, and not administering thromboprophylaxis in all patients.",
        ashDecision: "NoRx",
        category: "Asymptomatic individuals with family history of VTE - PGM",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R11c",
        pVTE: 0.05,
        Tp: 0.5,
        RRt: 12.17,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with VTE and Protein C deficiency who have a minor provoking VTE risk factor.",
        ashRec: "The ASH guideline panel suggests testing for the thrombophilia known in the family and use thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Asymptomatic individuals with family history of VTE - Protein C",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R11d",
        pVTE: 0.05,
        Tp: 0.5,
        RRt: 7.47,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with VTE and Protein S deficiency who have a minor provoking VTE risk factor.",
        ashRec: "The ASH guideline panel suggests testing for the thrombophilia known in the family and use thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Asymptomatic individuals with family history of VTE - Protein S",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R11e",
        pVTE: 0.05,
        Tp: 0.5,
        RRt: 5.98,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with VTE and Antithrombin deficiency who have a minor provoking VTE risk factor.",
        ashRec: "The ASH guideline panel suggests testing for the thrombophilia known in the family and use thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Asymptomatic individuals with family history of VTE - Antithrombin",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R12a",
        pVTE: 0.015,
        Tp: 0.512,
        RRt: 2.82,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with VTE and FVL - testing for all hereditary thrombophilias (panel).",
        ashRec: "The ASH guideline panel suggests not testing for all hereditary thrombophilias to guide thromboprophylaxis.",
        ashDecision: "NoRx",
        category: "Asymptomatic individuals - thrombophilia panel testing",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R12b",
        pVTE: 0.015,
        Tp: 0.524,
        RRt: 2.55,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with VTE and PGM - testing for all hereditary thrombophilias (panel).",
        ashRec: "The ASH guideline panel suggests not testing for all hereditary thrombophilias to guide thromboprophylaxis.",
        ashDecision: "NoRx",
        category: "Asymptomatic individuals - thrombophilia panel testing",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R12c",
        pVTE: 0.05,
        Tp: 0.533,
        RRt: 11.76,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with VTE and Protein C deficiency - testing for all hereditary thrombophilias (panel).",
        ashRec: "The ASH guideline panel suggests testing for all hereditary thrombophilias and use thromboprophylaxis in individuals positive for any thrombophilia.",
        ashDecision: "Test",
        category: "Asymptomatic individuals - thrombophilia panel testing",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R12d",
        pVTE: 0.05,
        Tp: 0.533,
        RRt: 7.36,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with VTE and Protein S deficiency - testing for all hereditary thrombophilias (panel).",
        ashRec: "The ASH guideline panel suggests testing for all hereditary thrombophilias and use thromboprophylaxis in individuals positive for any thrombophilia.",
        ashDecision: "Test",
        category: "Asymptomatic individuals - thrombophilia panel testing",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R12e",
        pVTE: 0.05,
        Tp: 0.534,
        RRt: 5.98,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with VTE and Antithrombin deficiency - testing for all hereditary thrombophilias (panel).",
        ashRec: "The ASH guideline panel suggests testing for all hereditary thrombophilias and use thromboprophylaxis in individuals positive for any thrombophilia.",
        ashDecision: "Test",
        category: "Asymptomatic individuals - thrombophilia panel testing",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R13",
        pVTE: 0.012,
        Tp: 0.142,
        RRt: 3.89,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Individuals with a family history of VTE and unknown thrombophilia status who have a minor provoking VTE risk factor.",
        ashRec: "The ASH guideline panel suggests not testing for thrombophilia.",
        ashDecision: "NoRx",
        category: "Asymptomatic individuals - unknown thrombophilia status",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R14a",
        pVTE: 0.015,
        Tp: 0.5,
        RRt: 2.71,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Individuals with a family history of FVL but no VTE who have a minor provoking VTE risk factor.",
        ashRec: "The ASH guideline panel suggests not testing for thrombophilia.",
        ashDecision: "NoRx",
        category: "Family history of thrombophilia but no VTE",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R14b",
        pVTE: 0.015,
        Tp: 0.5,
        RRt: 2.35,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Individuals with a family history of PGM but no VTE who have a minor provoking VTE risk factor.",
        ashRec: "The ASH guideline panel suggests not testing for thrombophilia.",
        ashDecision: "NoRx",
        category: "Family history of thrombophilia but no VTE",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R14c",
        pVTE: 0.05,
        Tp: 0.5,
        RRt: 12.17,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with Protein C deficiency (no VTE) who have a minor provoking VTE risk factor.",
        ashRec: "The ASH guideline panel suggests testing for the thrombophilia known in the family and use thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Family history of thrombophilia but no VTE - first-degree",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R14d",
        pVTE: 0.05,
        Tp: 0.5,
        RRt: 7.47,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with Protein S deficiency (no VTE) who have a minor provoking VTE risk factor.",
        ashRec: "The ASH guideline panel suggests testing for the thrombophilia known in the family and use thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Family history of thrombophilia but no VTE - first-degree",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R14e",
        pVTE: 0.05,
        Tp: 0.5,
        RRt: 5.98,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "First-degree relatives of patients with Antithrombin deficiency (no VTE) who have a minor provoking VTE risk factor.",
        ashRec: "The ASH guideline panel suggests testing for the thrombophilia known in the family and use thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Family history of thrombophilia but no VTE - first-degree",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R14f",
        pVTE: 0.025,
        Tp: 0.25,
        RRt: 12.17,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Second-degree relatives of patients with Protein C deficiency (no VTE) who have a minor provoking VTE risk factor.",
        ashRec: "Either test or do not test for the thrombophilia known in the family to guide the use of thromboprophylaxis.",
        ashDecision: "Test",
        category: "Family history of thrombophilia but no VTE - second-degree",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R14g",
        pVTE: 0.025,
        Tp: 0.25,
        RRt: 7.47,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Second-degree relatives of patients with Protein S deficiency (no VTE) who have a minor provoking VTE risk factor.",
        ashRec: "Either test or do not test for the thrombophilia known in the family to guide the use of thromboprophylaxis.",
        ashDecision: "Test",
        category: "Family history of thrombophilia but no VTE - second-degree",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },
    {
        id: "R14h",
        pVTE: 0.025,
        Tp: 0.25,
        RRt: 5.98,
        RRrx: 0.54,
        H_low: 0.004,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Second-degree relatives of patients with Antithrombin deficiency (no VTE) who have a minor provoking VTE risk factor.",
        ashRec: "Either test or do not test for the thrombophilia known in the family to guide the use of thromboprophylaxis.",
        ashDecision: "Test",
        category: "Family history of thrombophilia but no VTE - second-degree",
        group: "R11-R14",
        hasBleedingRiskOption: false
    },

    // ==================== R15-R20: Women Considering COC or HRT ====================
    // Note: These are "reversed" - treatment (COC/HRT) INCREASES VTE risk
    {
        id: "R15",
        pVTE: 0.00035,
        Tp: 0.0685,
        RRt: 5.89,
        RRrx: 3.5,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women from the general population considering combined oral contraceptives (COCs).",
        ashRec: "The ASH guideline panel recommends not performing thrombophilia testing to guide the use of COC and administering COC in all (strong recommendation).",
        ashDecision: "Rx",
        category: "Women considering COC or HRT",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "COC"
    },
    {
        id: "R16a",
        pVTE: 0.002,
        Tp: 0.0685,
        RRt: 1.8,
        RRrx: 2.22,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women from the general population considering HRT (estrogen alone).",
        ashRec: "The ASH guideline panel suggests not performing thrombophilia testing to guide the use of HRT and administering treatment to all.",
        ashDecision: "Rx",
        category: "Women considering COC or HRT",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT (estrogen alone)"
    },
    {
        id: "R16b",
        pVTE: 0.002,
        Tp: 0.0685,
        RRt: 1.8,
        RRrx: 4.28,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women from the general population considering HRT (estrogen + progestin).",
        ashRec: "The ASH guideline panel suggests not performing thrombophilia testing to guide the use of HRT and administering treatment to all.",
        ashDecision: "Rx",
        category: "Women considering COC or HRT",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT (estrogen + progestin)"
    },
    {
        id: "R17",
        pVTE: 0.0012,
        Tp: 0.142,
        RRt: 3.87,
        RRrx: 3.5,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with a family history of VTE and unknown thrombophilia status in the family who are considering using COCs.",
        ashRec: "The ASH guideline panel suggests not testing for hereditary thrombophilia to guide the use of COC and administering COC to all.",
        ashDecision: "Rx",
        category: "Women considering COC - family history VTE",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "COC"
    },
    {
        id: "R18a",
        pVTE: 0.003,
        Tp: 0.142,
        RRt: 2.08,
        RRrx: 2.22,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with a family history of VTE and unknown thrombophilia considering HRT (estrogen alone).",
        ashRec: "The ASH guideline panel suggests not performing thrombophilia testing to guide the use of HRT and administering HRT to all.",
        ashDecision: "Rx",
        category: "Women considering HRT - family history VTE",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT (estrogen alone)"
    },
    {
        id: "R18b",
        pVTE: 0.003,
        Tp: 0.142,
        RRt: 2.08,
        RRrx: 4.28,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with a family history of VTE and unknown thrombophilia considering HRT (estrogen + progestin).",
        ashRec: "The ASH guideline panel suggests not performing thrombophilia testing to guide the use of HRT and administering HRT to all.",
        ashDecision: "Rx",
        category: "Women considering HRT - family history VTE",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT (estrogen + progestin)"
    },
    {
        id: "R19a",
        pVTE: 0.0025,
        Tp: 0.5,
        RRt: 2.71,
        RRrx: 3.5,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known FVL considering COCs.",
        ashRec: "The ASH guideline panel suggests not testing for thrombophilia.",
        ashDecision: "Rx",
        category: "Women considering COC - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "COC"
    },
    {
        id: "R19b",
        pVTE: 0.0025,
        Tp: 0.5,
        RRt: 2.35,
        RRrx: 3.5,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known PGM considering COCs.",
        ashRec: "The ASH guideline panel suggests not testing for thrombophilia.",
        ashDecision: "Rx",
        category: "Women considering COC - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "COC"
    },
    {
        id: "R19c",
        pVTE: 0.0084,
        Tp: 0.5,
        RRt: 12.07,
        RRrx: 3.5,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known Protein C deficiency considering COCs.",
        ashRec: "The ASH guideline panel suggests testing for thrombophilia and avoid COCs in women with thrombophilia.",
        ashDecision: "Test",
        category: "Women considering COC - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "COC"
    },
    {
        id: "R19d",
        pVTE: 0.0063,
        Tp: 0.5,
        RRt: 7.24,
        RRrx: 3.5,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known Protein S deficiency considering COCs.",
        ashRec: "The ASH guideline panel suggests testing for thrombophilia and avoid COCs in women with thrombophilia.",
        ashDecision: "Test",
        category: "Women considering COC - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "COC"
    },
    {
        id: "R19e",
        pVTE: 0.0049,
        Tp: 0.5,
        RRt: 5.98,
        RRrx: 3.5,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known Antithrombin deficiency considering COCs.",
        ashRec: "The ASH guideline panel suggests testing for thrombophilia and avoid COCs in women with thrombophilia.",
        ashDecision: "Test",
        category: "Women considering COC - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "COC"
    },
    {
        id: "R20a",
        pVTE: 0.0025,
        Tp: 0.5,
        RRt: 2.6,
        RRrx: 2.22,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known FVL considering HRT (estrogen alone).",
        ashRec: "The ASH guideline panel suggests not testing for thrombophilia.",
        ashDecision: "Rx",
        category: "Women considering HRT - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT"
    },
    {
        id: "R20b",
        pVTE: 0.0025,
        Tp: 0.5,
        RRt: 2.6,
        RRrx: 4.28,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known FVL considering HRT (estrogen + progestin).",
        ashRec: "The ASH guideline panel suggests not testing for thrombophilia.",
        ashDecision: "Rx",
        category: "Women considering HRT - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT"
    },
    {
        id: "R20c",
        pVTE: 0.0025,
        Tp: 0.5,
        RRt: 0.8,
        RRrx: 2.22,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known PGM considering HRT (estrogen alone).",
        ashRec: "The ASH guideline panel suggests not testing for thrombophilia.",
        ashDecision: "Rx",
        category: "Women considering HRT - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT"
    },
    {
        id: "R20d",
        pVTE: 0.0025,
        Tp: 0.5,
        RRt: 0.8,
        RRrx: 4.28,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known PGM considering HRT (estrogen + progestin).",
        ashRec: "The ASH guideline panel suggests not testing for thrombophilia.",
        ashDecision: "Rx",
        category: "Women considering HRT - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT"
    },
    {
        id: "R20e",
        pVTE: 0.0084,
        Tp: 0.5,
        RRt: 1.7,
        RRrx: 2.22,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known Protein C deficiency considering HRT (estrogen alone).",
        ashRec: "The ASH guideline panel suggests testing for thrombophilia and avoid HRT in women with thrombophilia.",
        ashDecision: "Test",
        category: "Women considering HRT - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT"
    },
    {
        id: "R20f",
        pVTE: 0.0084,
        Tp: 0.5,
        RRt: 1.7,
        RRrx: 4.28,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known Protein C deficiency considering HRT (estrogen + progestin).",
        ashRec: "The ASH guideline panel suggests testing for thrombophilia and avoid HRT in women with thrombophilia.",
        ashDecision: "Test",
        category: "Women considering HRT - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT"
    },
    {
        id: "R20g",
        pVTE: 0.0063,
        Tp: 0.5,
        RRt: 1.8,
        RRrx: 2.22,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known Protein S deficiency considering HRT (estrogen alone).",
        ashRec: "The ASH guideline panel suggests testing for thrombophilia and avoid HRT in women with thrombophilia.",
        ashDecision: "Test",
        category: "Women considering HRT - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT"
    },
    {
        id: "R20h",
        pVTE: 0.0063,
        Tp: 0.5,
        RRt: 1.8,
        RRrx: 4.28,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known Protein S deficiency considering HRT (estrogen + progestin).",
        ashRec: "The ASH guideline panel suggests testing for thrombophilia and avoid HRT in women with thrombophilia.",
        ashDecision: "Test",
        category: "Women considering HRT - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT"
    },
    {
        id: "R20i",
        pVTE: 0.0049,
        Tp: 0.5,
        RRt: 1.9,
        RRrx: 2.22,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known Antithrombin deficiency considering HRT (estrogen alone).",
        ashRec: "The ASH guideline panel suggests testing for thrombophilia and avoid HRT in women with thrombophilia.",
        ashDecision: "Test",
        category: "Women considering HRT - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT"
    },
    {
        id: "R20j",
        pVTE: 0.0049,
        Tp: 0.5,
        RRt: 1.9,
        RRrx: 4.28,
        H_low: 0.005,
        H_high: null,
        RRbleed: 2.17,
        decimals: 4,
        description: "Women with family history of VTE and known Antithrombin deficiency considering HRT (estrogen + progestin).",
        ashRec: "The ASH guideline panel suggests testing for thrombophilia and avoid HRT in women with thrombophilia.",
        ashDecision: "Test",
        category: "Women considering HRT - known thrombophilia in family",
        group: "R15-R20",
        hasBleedingRiskOption: false,
        isReversed: true,
        treatmentName: "HRT"
    },

    // ==================== R21-R23: Women Planning Pregnancy ====================
    {
        id: "R21a",
        pVTE: 0.05,
        Tp: 0.5,
        RRt: 34.4,
        RRrx: 0.54,
        H_low: 0.02,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and known homozygous FVL planning pregnancy - antepartum prophylaxis.",
        ashRec: "Test for the thrombophilia known in the family and use antepartum thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Women planning pregnancy - antepartum",
        group: "R21-R23",
        hasBleedingRiskOption: false
    },
    {
        id: "R21b",
        pVTE: 0.05,
        Tp: 0.5,
        RRt: 6.74,
        RRrx: 0.54,
        H_low: 0.02,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and known combination of FVL and PGM planning pregnancy - antepartum prophylaxis.",
        ashRec: "Test for the thrombophilia known in the family and use antepartum thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Women planning pregnancy - antepartum",
        group: "R21-R23",
        hasBleedingRiskOption: false
    },
    {
        id: "R21c",
        pVTE: 0.05,
        Tp: 0.5,
        RRt: 4.69,
        RRrx: 0.54,
        H_low: 0.02,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and known heterozygous FVL planning pregnancy - antepartum prophylaxis.",
        ashRec: "Do not use antepartum prophylaxis.",
        ashDecision: "NoRx",
        category: "Women planning pregnancy - antepartum",
        group: "R21-R23",
        hasBleedingRiskOption: false
    },
    {
        id: "R21d",
        pVTE: 0.025,
        Tp: 0.5,
        RRt: 4.83,
        RRrx: 0.54,
        H_low: 0.02,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and known heterozygous PGM planning pregnancy - antepartum prophylaxis.",
        ashRec: "Do not use antepartum prophylaxis.",
        ashDecision: "NoRx",
        category: "Women planning pregnancy - antepartum",
        group: "R21-R23",
        hasBleedingRiskOption: false
    },
    {
        id: "R21e",
        pVTE: 0.025,
        Tp: 0.5,
        RRt: 3.19,
        RRrx: 0.54,
        H_low: 0.02,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and known Protein S deficiency planning pregnancy - antepartum prophylaxis.",
        ashRec: "Either test or do not test for the thrombophilia known in the family to guide antepartum prophylaxis.",
        ashDecision: "Test",
        category: "Women planning pregnancy - antepartum",
        group: "R21-R23",
        hasBleedingRiskOption: false
    },
    {
        id: "R22a",
        pVTE: 0.03,
        Tp: 0.5,
        RRt: 34.4,
        RRrx: 0.54,
        H_low: 0.002,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and known homozygous FVL planning pregnancy - postpartum prophylaxis.",
        ashRec: "Test for the thrombophilia known in the family and use postpartum thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Women planning pregnancy - postpartum",
        group: "R21-R23",
        hasBleedingRiskOption: false
    },
    {
        id: "R22b",
        pVTE: 0.03,
        Tp: 0.5,
        RRt: 6.74,
        RRrx: 0.54,
        H_low: 0.002,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and known combination of FVL and PGM planning pregnancy - postpartum prophylaxis.",
        ashRec: "Test for the thrombophilia known in the family and use postpartum thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Women planning pregnancy - postpartum",
        group: "R21-R23",
        hasBleedingRiskOption: false
    },
    {
        id: "R22c",
        pVTE: 0.03,
        Tp: 0.5,
        RRt: 4.69,
        RRrx: 0.54,
        H_low: 0.002,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and known Antithrombin deficiency planning pregnancy - postpartum prophylaxis.",
        ashRec: "Test for the thrombophilia known in the family and use postpartum thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Women planning pregnancy - postpartum",
        group: "R21-R23",
        hasBleedingRiskOption: false
    },
    {
        id: "R22d",
        pVTE: 0.03,
        Tp: 0.5,
        RRt: 4.83,
        RRrx: 0.54,
        H_low: 0.002,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and known Protein C deficiency planning pregnancy - postpartum prophylaxis.",
        ashRec: "Test for the thrombophilia known in the family and use postpartum thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Women planning pregnancy - postpartum",
        group: "R21-R23",
        hasBleedingRiskOption: false
    },
    {
        id: "R22e",
        pVTE: 0.03,
        Tp: 0.5,
        RRt: 3.19,
        RRrx: 0.54,
        H_low: 0.002,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and known Protein S deficiency planning pregnancy - postpartum prophylaxis.",
        ashRec: "Test for the thrombophilia known in the family and use postpartum thromboprophylaxis in individuals positive for thrombophilia.",
        ashDecision: "Test",
        category: "Women planning pregnancy - postpartum",
        group: "R21-R23",
        hasBleedingRiskOption: false
    },
    {
        id: "R23a",
        pVTE: 0.012,
        Tp: 0.142,
        RRt: 3.89,
        RRrx: 0.54,
        H_low: 0.02,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and unknown thrombophilia status planning pregnancy - antepartum prophylaxis.",
        ashRec: "Test for hereditary thrombophilia to guide antepartum prophylaxis.",
        ashDecision: "Test",
        category: "Women planning pregnancy - unknown status",
        group: "R21-R23",
        hasBleedingRiskOption: false
    },
    {
        id: "R23b",
        pVTE: 0.012,
        Tp: 0.142,
        RRt: 3.89,
        RRrx: 0.54,
        H_low: 0.002,
        H_high: null,
        RRbleed: 2.09,
        decimals: 2,
        description: "Women with family history of VTE and unknown thrombophilia status planning pregnancy - postpartum prophylaxis.",
        ashRec: "Test for hereditary thrombophilia and use postpartum thromboprophylaxis in individuals positive for high-risk thrombophilia.",
        ashDecision: "Test",
        category: "Women planning pregnancy - unknown status",
        group: "R21-R23",
        hasBleedingRiskOption: false
    }
];

// Export for use in calculator.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { RECOMMENDATIONS };
}
